### PR TITLE
Docker: Attempt to build for ARM as well

### PR DESCRIPTION
**Pull request by markstos**
I'd like to try running this on Asahi Linux.

### CODE REVIEW

**Comment by markstos** [comment]
Thank you! Docker Hub is showing a successful build of arm64:

https://hub.docker.com/r/kensand/rss-lemmy-bot/tags

**Comment by kensand** [comment]
No thank _you_ for contributing :smile: TBH, I don't use this bot anymore, but am happy to continue maintaining it for others :+1:

**Comment by markstos** [comment]
Do you use a different RSS to Lemmy bot instead, or just don't use one now?

**Comment by kensand** [comment]
Just don't use one now - I briefly hosted my own Lemmy instance for personal use (and used this bot heavily to populate it), but there's just too many risks for me related to self-hosting Lemmy that I shut it down. Maybe one of these days I'll set up a community on someone else's instance for local (to me) news and start running the bot again though :shrug:

**Comment by markstos** [comment]
That's what I might try it for-- aggregating local news feeds. Seems like a good use of Lemmy... and this bot!

**Pull request merged**
